//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaServiceRef
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CinemaServiceRef.ICinemaService")]
    public interface ICinemaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/MakeReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task MakeReservationAsync(System.DateTime dateTime, int userId, int playingId, string reservedSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/CancelReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task CancelReservationAsync(int reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetReservations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetReservationsAsync(int playingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetRepertoire", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CinemaServiceRef.GetRepertoireResponse> GetRepertoireAsync(CinemaServiceRef.GetRepertoireRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetMovieImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMovieImageAsync(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/CanMakeReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CanMakeReservationAsync(int playingId, string seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/CanEditReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CanEditReservationAsync(int reservationId, int playingId, string seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetPlayingDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CinemaServiceRef.Playing> GetPlayingDetailsAsync(int playingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllUserReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CinemaServiceRef.GetAllUserReservationResponse> GetAllUserReservationAsync(CinemaServiceRef.GetAllUserReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetUserReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CinemaServiceRef.GetUserReservationResponse> GetUserReservationAsync(CinemaServiceRef.GetUserReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CinemaServiceRef.Reservation> GetReservationAsync(int userId, int reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/EditReservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task EditReservationAsync(int userId, int playingId, int reservationId, string seats);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Playing : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int idField;
        
        private int hallIdField;
        
        private CinemaHall hallField;
        
        private int movieIdField;
        
        private Movie movieField;
        
        private System.DateTime dateField;
        
        private PlayingState stateField;
        
        private float ticketCostField;
        
        private Reservation[] reservationsField;
        
        private string actualReservationsField;
        
        private bool hasFreeReservationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HallId
        {
            get
            {
                return this.hallIdField;
            }
            set
            {
                this.hallIdField = value;
                this.RaisePropertyChanged("HallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CinemaHall Hall
        {
            get
            {
                return this.hallField;
            }
            set
            {
                this.hallField = value;
                this.RaisePropertyChanged("Hall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int MovieId
        {
            get
            {
                return this.movieIdField;
            }
            set
            {
                this.movieIdField = value;
                this.RaisePropertyChanged("MovieId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Movie Movie
        {
            get
            {
                return this.movieField;
            }
            set
            {
                this.movieField = value;
                this.RaisePropertyChanged("Movie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public PlayingState State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float TicketCost
        {
            get
            {
                return this.ticketCostField;
            }
            set
            {
                this.ticketCostField = value;
                this.RaisePropertyChanged("TicketCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=8)]
        public Reservation[] Reservations
        {
            get
            {
                return this.reservationsField;
            }
            set
            {
                this.reservationsField = value;
                this.RaisePropertyChanged("Reservations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ActualReservations
        {
            get
            {
                return this.actualReservationsField;
            }
            set
            {
                this.actualReservationsField = value;
                this.RaisePropertyChanged("ActualReservations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool HasFreeReservations
        {
            get
            {
                return this.hasFreeReservationsField;
            }
            set
            {
                this.hasFreeReservationsField = value;
                this.RaisePropertyChanged("HasFreeReservations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CinemaHall : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int idField;
        
        private int numberField;
        
        private HallType typeField;
        
        private int columnsField;
        
        private int rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public HallType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Columns
        {
            get
            {
                return this.columnsField;
            }
            set
            {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Rows
        {
            get
            {
                return this.rowsField;
            }
            set
            {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum HallType
    {
        
        /// <remarks/>
        Small,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Large,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int idField;
        
        private string nameField;
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int idField;
        
        private int userIdField;
        
        private User userField;
        
        private int playingIdField;
        
        private Playing playingField;
        
        private System.DateTime dateField;
        
        private float reservationCostField;
        
        private int seatCountField;
        
        private string seatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public User User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PlayingId
        {
            get
            {
                return this.playingIdField;
            }
            set
            {
                this.playingIdField = value;
                this.RaisePropertyChanged("PlayingId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Playing Playing
        {
            get
            {
                return this.playingField;
            }
            set
            {
                this.playingField = value;
                this.RaisePropertyChanged("Playing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float ReservationCost
        {
            get
            {
                return this.reservationCostField;
            }
            set
            {
                this.reservationCostField = value;
                this.RaisePropertyChanged("ReservationCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int SeatCount
        {
            get
            {
                return this.seatCountField;
            }
            set
            {
                this.seatCountField = value;
                this.RaisePropertyChanged("SeatCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Seats
        {
            get
            {
                return this.seatsField;
            }
            set
            {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Movie : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int idField;
        
        private string nameField;
        
        private string directorField;
        
        private string scriptField;
        
        private string genreField;
        
        private float gradeField;
        
        private string durationField;
        
        private int productionYearField;
        
        private string descriptionShortField;
        
        private string descriptionLongField;
        
        private string imagePathField;
        
        private string imageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Director
        {
            get
            {
                return this.directorField;
            }
            set
            {
                this.directorField = value;
                this.RaisePropertyChanged("Director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Script
        {
            get
            {
                return this.scriptField;
            }
            set
            {
                this.scriptField = value;
                this.RaisePropertyChanged("Script");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Genre
        {
            get
            {
                return this.genreField;
            }
            set
            {
                this.genreField = value;
                this.RaisePropertyChanged("Genre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
                this.RaisePropertyChanged("Grade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=6)]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ProductionYear
        {
            get
            {
                return this.productionYearField;
            }
            set
            {
                this.productionYearField = value;
                this.RaisePropertyChanged("ProductionYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DescriptionShort
        {
            get
            {
                return this.descriptionShortField;
            }
            set
            {
                this.descriptionShortField = value;
                this.RaisePropertyChanged("DescriptionShort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DescriptionLong
        {
            get
            {
                return this.descriptionLongField;
            }
            set
            {
                this.descriptionLongField = value;
                this.RaisePropertyChanged("DescriptionLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ImagePath
        {
            get
            {
                return this.imagePathField;
            }
            set
            {
                this.imagePathField = value;
                this.RaisePropertyChanged("ImagePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PlayingState
    {
        
        /// <remarks/>
        ComingSoon,
        
        /// <remarks/>
        Playing,
        
        /// <remarks/>
        Ended,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRepertoire", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRepertoireRequest
    {
        
        public GetRepertoireRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRepertoireResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRepertoireResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CinemaServiceRef.Playing[] GetRepertoireResult;
        
        public GetRepertoireResponse()
        {
        }
        
        public GetRepertoireResponse(CinemaServiceRef.Playing[] GetRepertoireResult)
        {
            this.GetRepertoireResult = GetRepertoireResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUserReservation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllUserReservationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int userId;
        
        public GetAllUserReservationRequest()
        {
        }
        
        public GetAllUserReservationRequest(int userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUserReservationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllUserReservationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CinemaServiceRef.Reservation[] GetAllUserReservationResult;
        
        public GetAllUserReservationResponse()
        {
        }
        
        public GetAllUserReservationResponse(CinemaServiceRef.Reservation[] GetAllUserReservationResult)
        {
            this.GetAllUserReservationResult = GetAllUserReservationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserReservationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int playingId;
        
        public GetUserReservationRequest()
        {
        }
        
        public GetUserReservationRequest(int userId, int playingId)
        {
            this.userId = userId;
            this.playingId = playingId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserReservationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CinemaServiceRef.Reservation[] GetUserReservationResult;
        
        public GetUserReservationResponse()
        {
        }
        
        public GetUserReservationResponse(CinemaServiceRef.Reservation[] GetUserReservationResult)
        {
            this.GetUserReservationResult = GetUserReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICinemaServiceChannel : CinemaServiceRef.ICinemaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CinemaServiceClient : System.ServiceModel.ClientBase<CinemaServiceRef.ICinemaService>, CinemaServiceRef.ICinemaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CinemaServiceClient() : 
                base(CinemaServiceClient.GetDefaultBinding(), CinemaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICinemaService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CinemaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CinemaServiceClient.GetBindingForEndpoint(endpointConfiguration), CinemaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CinemaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CinemaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CinemaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CinemaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CinemaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task MakeReservationAsync(System.DateTime dateTime, int userId, int playingId, string reservedSeats)
        {
            return base.Channel.MakeReservationAsync(dateTime, userId, playingId, reservedSeats);
        }
        
        public System.Threading.Tasks.Task CancelReservationAsync(int reservationId)
        {
            return base.Channel.CancelReservationAsync(reservationId);
        }
        
        public System.Threading.Tasks.Task<string> GetReservationsAsync(int playingId)
        {
            return base.Channel.GetReservationsAsync(playingId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaServiceRef.GetRepertoireResponse> CinemaServiceRef.ICinemaService.GetRepertoireAsync(CinemaServiceRef.GetRepertoireRequest request)
        {
            return base.Channel.GetRepertoireAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaServiceRef.GetRepertoireResponse> GetRepertoireAsync()
        {
            CinemaServiceRef.GetRepertoireRequest inValue = new CinemaServiceRef.GetRepertoireRequest();
            return ((CinemaServiceRef.ICinemaService)(this)).GetRepertoireAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> GetMovieImageAsync(int movieId)
        {
            return base.Channel.GetMovieImageAsync(movieId);
        }
        
        public System.Threading.Tasks.Task<int> CanMakeReservationAsync(int playingId, string seats)
        {
            return base.Channel.CanMakeReservationAsync(playingId, seats);
        }
        
        public System.Threading.Tasks.Task<int> CanEditReservationAsync(int reservationId, int playingId, string seats)
        {
            return base.Channel.CanEditReservationAsync(reservationId, playingId, seats);
        }
        
        public System.Threading.Tasks.Task<CinemaServiceRef.Playing> GetPlayingDetailsAsync(int playingId)
        {
            return base.Channel.GetPlayingDetailsAsync(playingId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaServiceRef.GetAllUserReservationResponse> CinemaServiceRef.ICinemaService.GetAllUserReservationAsync(CinemaServiceRef.GetAllUserReservationRequest request)
        {
            return base.Channel.GetAllUserReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaServiceRef.GetAllUserReservationResponse> GetAllUserReservationAsync(int userId)
        {
            CinemaServiceRef.GetAllUserReservationRequest inValue = new CinemaServiceRef.GetAllUserReservationRequest();
            inValue.userId = userId;
            return ((CinemaServiceRef.ICinemaService)(this)).GetAllUserReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaServiceRef.GetUserReservationResponse> CinemaServiceRef.ICinemaService.GetUserReservationAsync(CinemaServiceRef.GetUserReservationRequest request)
        {
            return base.Channel.GetUserReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaServiceRef.GetUserReservationResponse> GetUserReservationAsync(int userId, int playingId)
        {
            CinemaServiceRef.GetUserReservationRequest inValue = new CinemaServiceRef.GetUserReservationRequest();
            inValue.userId = userId;
            inValue.playingId = playingId;
            return ((CinemaServiceRef.ICinemaService)(this)).GetUserReservationAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<CinemaServiceRef.Reservation> GetReservationAsync(int userId, int reservationId)
        {
            return base.Channel.GetReservationAsync(userId, reservationId);
        }
        
        public System.Threading.Tasks.Task EditReservationAsync(int userId, int playingId, int reservationId, string seats)
        {
            return base.Channel.EditReservationAsync(userId, playingId, reservationId, seats);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICinemaService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICinemaService_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:14594/CinemaService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CinemaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICinemaService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CinemaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICinemaService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICinemaService_soap,
        }
    }
}
